/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Royal
 */
public class AddBooks extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddBooks
     */
    public AddBooks() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        b_id = new javax.swing.JTextField();
        b_name = new javax.swing.JTextField();
        B_code = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        B_pub = new javax.swing.JTextArea();
        b_type = new javax.swing.JComboBox<>();
        catg = new javax.swing.JComboBox<>();
        date = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        year = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setForeground(new java.awt.Color(0, 102, 153));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 130, 40));

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 100, 130, 40));

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 130, 40));

        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 250, 180));

        jTable1.setForeground(new java.awt.Color(0, 51, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID#", "Book Name", "Book Code", "Date", "Category", "Book Type", "Publishers", "Price"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 930, 140));

        b_id.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jPanel1.add(b_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, 30));

        b_name.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        b_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nameActionPerformed(evt);
            }
        });
        jPanel1.add(b_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 150, 30));

        B_code.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jPanel1.add(B_code, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 150, 30));

        price.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jPanel1.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 170, 30));

        B_pub.setColumns(20);
        B_pub.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        B_pub.setRows(5);
        jScrollPane1.setViewportView(B_pub);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 240, -1));

        b_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Borrow", "Read Only" }));
        jPanel1.add(b_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 170, -1));

        catg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Technology", "Science", "History", "Arts", "Others" }));
        jPanel1.add(catg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 120, -1));

        date.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 60, -1));

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "may", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "December" }));
        jPanel1.add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1990", "1992", "1993", "1994", "1995", "1996", "1998", "1999", "2000", "2091", "2002", "2003", "2004", "2005", "2006", "2007", "20008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017" }));
        jPanel1.add(year, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 70, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setText("Book ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setText("Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel8.setText("Book Code");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel9.setText("Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel10.setText("Category");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel11.setText("Book Type");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel12.setText("Publishers");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel13.setText("Price");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Books");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, -1));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 950, 200));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 450));

        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 50));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 950, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                
        if(b_id.getText().equals("")||b_name.getText().equals("") || B_code.getText().equals("")|| date.getSelectedItem().toString().equals(0) ||  month.getSelectedItem().toString().equals(0)||year.getSelectedItem().toString().equals(0) ||catg.getSelectedItem().toString().equals(0)|| b_type.getSelectedItem().toString().equals(0)||B_pub.getText().equals("")||price.getText().equals("") )
        {
               JOptionPane.showMessageDialog(this, "Please enter all fields!");
        }
        else
        {
         //     String data[]={Mem_ID.getText(),mem_Name.getText(),jnic.getText(),jdate.getSelectedItem().toString(),jgender.getSelectedItem().toString(),jcontact.getText(),jaddress.getText(),jmem_type.getSelectedItem().toString()};
                  String data[]={b_id.getText(),b_name.getText(),B_code.getText(),date.getSelectedItem().toString()+"/"+month.getSelectedItem().toString()+"/"+year.getSelectedItem().toString(),catg.getSelectedItem().toString(),b_type.getSelectedItem().toString(),B_pub.getText(),price.getText()};
   
            DefaultTableModel  tblModel = (DefaultTableModel) jTable1.getModel();
                tblModel.addRow(data);
                
                JOptionPane.showMessageDialog(this, "Book added Succcessfully");
                b_id.setText("");
                b_name.setText("");
                B_code.setText("");
                date.setSelectedIndex(0);
                month.setSelectedIndex(0);
                year.setSelectedIndex(0);
                catg.setSelectedIndex(0);
                 b_type.setSelectedIndex(0);
                B_pub.setText("");
                price.setText("");
             //   jaddress.setText("");
                
        }
            

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                int i= jTable1.getSelectedRow();
        DefaultTableModel model= ( DefaultTableModel) jTable1.getModel();

        if(i >=0)
        {
        model.setValueAt(b_id.getText(), i,0);
        model.setValueAt(b_name.getText(), i,1);
        model.setValueAt(B_code.getText(), i,2);
        model.setValueAt(date.getSelectedItem().toString()+"/"+month.getSelectedItem().toString()+"/"+year.getSelectedItem().toString(), i,3);
        model.setValueAt( catg.getSelectedItem(), i,4);
        model.setValueAt(b_type.getSelectedItem(), i,5);     
        model.setValueAt(B_pub.getText() , i,6);
        model.setValueAt( price.getText(), i,7);

  b_id.setText("");
                b_name.setText("");
                B_code.setText("");
                date.setSelectedIndex(0);
                month.setSelectedIndex(0);
                year.setSelectedIndex(0);

                catg.setSelectedIndex(0);
               b_type.setSelectedIndex(0);
                B_pub.setText("");
                price.setText("");
                 
  
    }                                        
        else{
        
            JOptionPane.showMessageDialog(null,"Error");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          DefaultTableModel model =(DefaultTableModel) jTable1.getModel();
        int selectedRowIndex = jTable1.getSelectedRow();
        model.removeRow(selectedRowIndex);
        
                JOptionPane.showMessageDialog(this, " Data is deleted Succcessfully");
                b_id.setText("");
                b_name.setText("");
                B_code.setText("");
                date.setSelectedIndex(0);
                month.setSelectedIndex(0);
                year.setSelectedIndex(0);
                catg.setSelectedIndex(0);
                b_type.setSelectedIndex(0);
                B_pub.setText("");
                price.setText("");
                
                

    }//GEN-LAST:event_jButton1ActionPerformed

    private void b_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b_nameActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
    //      String dob=jdate.getSelectedItem()+"/"+jmonth.getSelectedItem()+"/"+jdate.getSelectedItem();
                   int selectedRow=jTable1.getSelectedRow();
                   DefaultTableModel model= ( DefaultTableModel) jTable1.getModel();
                   b_id.setText(model.getValueAt(selectedRow, 0).toString());
                   b_name.setText(model.getValueAt(selectedRow, 1).toString());
                  B_code.setText(model.getValueAt(selectedRow, 2).toString());
              date.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
              month.setSelectedItem(model.getValueAt(selectedRow, 3).toString());//+"/"
              year.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
                  catg.setSelectedItem(model.getValueAt(selectedRow, 4).toString());
                  b_type.setSelectedItem(model.getValueAt(selectedRow, 5).toString());
             
                   B_pub.setText(model.getValueAt(selectedRow, 6).toString());
                  price.setText(model.getValueAt(selectedRow, 7).toString());
                   
        
    }//GEN-LAST:event_jTable1MouseClicked
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBooks().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField B_code;
    private javax.swing.JTextArea B_pub;
    private javax.swing.JTextField b_id;
    private javax.swing.JTextField b_name;
    private javax.swing.JComboBox<String> b_type;
    private javax.swing.JComboBox<String> catg;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField price;
    private javax.swing.JComboBox<String> year;
    // End of variables declaration//GEN-END:variables
}
