/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

//import java.util.ArrayList;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import javax.swing.JOptionPane;
/**
 *
 * @author Royal
 */
public class AddMember2 extends javax.swing.JInternalFrame {

   // ArrayList<Addm> memberlist;
  ///  String header[] = new String{"ID","Name"."NIC"."DOB"."Gender"."Email"."Contact"."Address"."Member type"};
 
    
    /**
     * Creates new form Borrow
     */
    public AddMember2() {
        initComponents();
     /*    memberlist = new ArrayList<>();
//         dtm= new DefaultTableModel();
dtm=(DefaultTableModel) jTable1.getModel();   
jTable1.setModel(dtm);
        this.setLocationRelativeTo(null);
    *///dtm=(DefaultTableModel) jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jdate = new javax.swing.JComboBox<>();
        jmonth = new javax.swing.JComboBox<>();
        jyear = new javax.swing.JComboBox<>();
        jgender = new javax.swing.JComboBox<>();
        Mem_ID = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        mem_Name = new javax.swing.JTextField();
        jnic = new javax.swing.JTextField();
        jemail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jaddress = new javax.swing.JTextArea();
        jcontact = new javax.swing.JTextField();
        jmem_type = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jmem_id = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel2 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID#", "Name", "NIC", "DOB", "Gender", "Email", "Contact", "Address", "Mem_type"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 297, 1000, 150));

        jButton3.setBackground(new java.awt.Color(102, 204, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 160, 40));

        jButton4.setBackground(new java.awt.Color(102, 204, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 160, 40));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 160, 40));

        jdate.setEditable(true);
        jdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 60, -1));

        jmonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "Jan", "Feb", "Mar", "Apr", "may", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "December" }));
        jPanel1.add(jmonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jyear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "1990", "1992", "1993", "1994", "1995", "1996", "1998", "1999", "2000", "2091", "2002", "2003", "2004", "2005" }));
        jPanel1.add(jyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 60, -1));

        jgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        jPanel1.add(jgender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 150, -1));
        jPanel1.add(Mem_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, -1));

        jTextField2.setText("jTextField1");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, -1));

        jTextField3.setText("jTextField1");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, -1));

        jTextField4.setText("jTextField1");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, -1));

        jTextField5.setText("jTextField1");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, -1));

        jTextField6.setText("jTextField1");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, -1));
        jPanel1.add(mem_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, -1));
        jPanel1.add(jnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));
        jPanel1.add(jemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 160, -1));

        jaddress.setColumns(20);
        jaddress.setRows(5);
        jScrollPane1.setViewportView(jaddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 166, 160, 50));
        jPanel1.add(jcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 160, -1));

        jmem_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Permanant", "Temporary" }));
        jPanel1.add(jmem_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 130, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel12.setText("Gender:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel4.setText("Member id");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel5.setText("Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel6.setText("NIC");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel7.setText("DOB :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel9.setText("Contact:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel10.setText("Address:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel11.setText("Member Type:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 140, 20));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 1100, 180));

        jmem_id.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jmem_id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jmem_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 1020, 230));
        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 290, 950, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        jLabel2.setText("Members");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model =(DefaultTableModel) jTable3.getModel();
        int selectedRowIndex = jTable3.getSelectedRow();
        model.removeRow(selectedRowIndex);
        
                JOptionPane.showMessageDialog(this, " Data is deleted Succcessfully");
                Mem_ID.setText("");
                mem_Name.setText("");
                jnic.setText("");
                jdate.setSelectedIndex(0);
                jmonth.setSelectedIndex(0);
                jyear.setSelectedIndex(0);

                jgender.setSelectedIndex(0);
                jemail.setText("");
                jcontact.setText("");
                jaddress.setText("");
                 jmem_type.setSelectedIndex(0);
        
    }//GEN-LAST:event_jButton1ActionPerformed

   /* public void date()
    {
 String  mdate=  jdate.getSelectedItem().toString()+"/"+jmonth.getSelectedItem().toString()+"/"+jyear.getSelectedItem().toString();
    }*/
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        
        if(Mem_ID.getText().equals("")||mem_Name.getText().equals("") || jnic.getText().equals("")|| jdate.getSelectedItem().toString().equals(0) || jgender.getSelectedItem().toString().equals(0) ||jemail.getText().equals("")|| jcontact.getText().equals("") || jaddress.getText().equals("") || jmem_type.getSelectedItem().toString().equals(0))
        {
               JOptionPane.showMessageDialog(this, "Please enter all fields!");
        }
        else
        {
         //     String data[]={Mem_ID.getText(),mem_Name.getText(),jnic.getText(),jdate.getSelectedItem().toString(),jgender.getSelectedItem().toString(),jcontact.getText(),jaddress.getText(),jmem_type.getSelectedItem().toString()};
                  String data[]={Mem_ID.getText(),mem_Name.getText(),jnic.getText(),jdate.getSelectedItem().toString()+"/"+jmonth.getSelectedItem().toString()+"/"+jyear.getSelectedItem().toString(),jgender.getSelectedItem().toString(), jemail.getText(),jcontact.getText(),jaddress.getText(),jmem_type.getSelectedItem().toString()};
   
            DefaultTableModel  tblModel = (DefaultTableModel) jTable3.getModel();
                tblModel.addRow(data);
                
                JOptionPane.showMessageDialog(this, "Add data Succcessfully");
                Mem_ID.setText("");
                mem_Name.setText("");
                jnic.setText("");
                jdate.setSelectedIndex(0);
                jmonth.setSelectedIndex(0);
                jyear.setSelectedIndex(0);

                jgender.setSelectedIndex(0);
                jemail.setText("");
                jcontact.setText("");
                jaddress.setText("");
                 jmem_type.setSelectedIndex(0);
        }
            
            
            
            /*String ID=jmem_id.getText(); 
String name=jname.getText();
String nic=jnic.getText();
String  gender=jgender.getSelectedItem().toString();
String  contact=jcontact.getText(); 
String email=jemail.getText();
String  address=jaddress.getText();
 String  mem_ty= jmem_type.getSelectedItem().toString();   
 dtm.setRowCount(0);
     for(int i=0; i < memberlist.size();i++)
     {
          Object[] obj={memberlist.get(i).ID,
              memberlist.get(i).name,memberlist.get(i).nic,memberlist.get(i).gender,
              memberlist.get(i).contact,memberlist.get(i).email,memberlist.get(i).address,memberlist.get(i).mem_ty}; 
  dtm.addRow(obj);
     }*/

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        String dob=jdate.getSelectedItem()+"/"+jmonth.getSelectedItem()+"/"+jdate.getSelectedItem();
                   int selectedRow=jTable3.getSelectedRow();
                   DefaultTableModel model= ( DefaultTableModel) jTable3.getModel();
                   Mem_ID.setText(model.getValueAt(selectedRow, 0).toString());
                   mem_Name.setText(model.getValueAt(selectedRow, 1).toString());
                   jnic.setText(model.getValueAt(selectedRow, 2).toString());
            //      jdate.setSelectedItem(model.getValueAt(selectedRow, 3).toString())+"/"jmonth.setSelectedItem(model.getValueAt(selectedRow, 3).toString())+"/"jmonth.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
                   jgender.setSelectedItem(model.getValueAt(selectedRow, 4).toString());
                  jemail.setText(model.getValueAt(selectedRow, 5).toString());
                   jcontact.setText(model.getValueAt(selectedRow, 6).toString());
                   jaddress.setText(model.getValueAt(selectedRow, 7).toString());
                   jmem_type.setSelectedItem(model.getValueAt(selectedRow, 8).toString());
                   
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int i= jTable3.getSelectedRow();
        DefaultTableModel model= ( DefaultTableModel) jTable3.getModel();

        if(i >=0)
        {
        model.setValueAt(Mem_ID.getText(), i,0);
        model.setValueAt(mem_Name.getText(), i,1);
        model.setValueAt(jnic.getText(), i,2);
        model.setValueAt(jdate.getSelectedItem().toString()+"/"+jmonth.getSelectedItem().toString()+"/"+jyear.getSelectedItem().toString(), i,3);
        model.setValueAt( jgender.getSelectedItem(), i,4);
        model.setValueAt(jemail.getText(), i,5);
         model.setValueAt( jcontact.getText(), i,6);
        model.setValueAt( jaddress.getText(), i,7);
        model.setValueAt( jmem_type.getSelectedItem(), i,8);
    }//GEN-LAST:event_jButton3ActionPerformed
        else{
        
            JOptionPane.showMessageDialog(null,"Error");
        }
    }


 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMember2().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Mem_ID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextArea jaddress;
    private javax.swing.JTextField jcontact;
    private javax.swing.JComboBox<String> jdate;
    private javax.swing.JTextField jemail;
    private javax.swing.JComboBox<String> jgender;
    private javax.swing.JLabel jmem_id;
    private javax.swing.JComboBox<String> jmem_type;
    private javax.swing.JComboBox<String> jmonth;
    private javax.swing.JTextField jnic;
    private javax.swing.JComboBox<String> jyear;
    private javax.swing.JTextField mem_Name;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
