/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import java.util.GregorianCalendar;
//import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.time;
import java.util.Calendar;

//import java.util.logging.Level;
//import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Royal
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        clock();
    }

    public void clock(){
    
        Thread clock = new Thread()
                {
                @Override
                public void run(){
                try{
                while(true)
                {
                Calendar cal=new GregorianCalendar();
                int day=cal.get(Calendar.DAY_OF_MONTH);
                 int month=cal.get(Calendar.MONTH)+1;
                  int year=cal.get(Calendar.YEAR);
                  
                  int second=cal.get(Calendar.SECOND);
                   int minute=cal.get(Calendar.MINUTE);
                    int hour=cal.get(Calendar.HOUR);
                    
                   Jtime.setText(hour+"-"+minute+ "-"+second);
                    Jdate.setText(day+"-"+ month+ "-"+year);
       
                sleep(1000);
                }
              }   catch (InterruptedException e){
                JOptionPane.showMessageDialog(rootPane, e);  
              }}
                };
        
                
                clock.start();
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Jdate = new javax.swing.JLabel();
        Jtime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_borrow = new javax.swing.JButton();
        btn_return = new javax.swing.JButton();
        btn_add_mem = new javax.swing.JButton();
        btn_add_book = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        homeDesktop = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 650));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Library Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        Jdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jdate.setText("Date");
        jPanel1.add(Jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 70, -1, -1));

        Jtime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Jtime.setText("Time");
        jPanel1.add(Jtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 70, -1, -1));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 70));

        btn_borrow.setBackground(new java.awt.Color(204, 204, 0));
        btn_borrow.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btn_borrow.setText("Borrow");
        btn_borrow.setFocusable(false);
        btn_borrow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_borrow.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_borrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrowActionPerformed(evt);
            }
        });
        jPanel1.add(btn_borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 160, -1));

        btn_return.setBackground(new java.awt.Color(255, 255, 0));
        btn_return.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btn_return.setText("return");
        btn_return.setFocusable(false);
        btn_return.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_return.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_returnActionPerformed(evt);
            }
        });
        jPanel1.add(btn_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 160, -1));

        btn_add_mem.setBackground(new java.awt.Color(255, 255, 0));
        btn_add_mem.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btn_add_mem.setText("Add Member");
        btn_add_mem.setFocusable(false);
        btn_add_mem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_add_mem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_add_mem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_memActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add_mem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 160, -1));

        btn_add_book.setBackground(new java.awt.Color(255, 255, 0));
        btn_add_book.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        btn_add_book.setText("Add Book");
        btn_add_book.setFocusable(false);
        btn_add_book.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_add_book.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_add_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_bookActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 160, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 200, 510));

        javax.swing.GroupLayout homeDesktopLayout = new javax.swing.GroupLayout(homeDesktop);
        homeDesktop.setLayout(homeDesktopLayout);
        homeDesktopLayout.setHorizontalGroup(
            homeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        homeDesktopLayout.setVerticalGroup(
            homeDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(homeDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 980, 490));

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\A3s\\library-relocation-jpg.jpg")); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 580));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
   

    private void btn_add_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_bookActionPerformed
        homeDesktop.removeAll();
       AddBooks ab= new AddBooks();
        homeDesktop.add(ab).setVisible(true);
    }//GEN-LAST:event_btn_add_bookActionPerformed

    private void btn_add_memActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_memActionPerformed
homeDesktop.removeAll();
       AddMember2 am= new  AddMember2();
    homeDesktop.add(am).setVisible(true);
    }//GEN-LAST:event_btn_add_memActionPerformed

    private void btn_borrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrowActionPerformed
        homeDesktop.removeAll();
      Borrow br= new Borrow();
        homeDesktop.add(br).setVisible(true);
    }//GEN-LAST:event_btn_borrowActionPerformed

    private void btn_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_returnActionPerformed
        homeDesktop.removeAll();
       Return r = new Return();
      homeDesktop.add(r).setVisible(true);
 
    }//GEN-LAST:event_btn_returnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jdate;
    private javax.swing.JLabel Jtime;
    private javax.swing.JButton btn_add_book;
    private javax.swing.JButton btn_add_mem;
    private javax.swing.JButton btn_borrow;
    private javax.swing.JButton btn_return;
    private javax.swing.JDesktopPane homeDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
